#!/usr/bin/env python3
"""
retroactive_pub_datetime.py — Retroactively adds publication datetime stamps
to all existing Anthology HTML pages.

For each HTML file in essays/, notes/, dispatches/, uk-politics/, us-sports/,
retrieves the first git commit timestamp for that file, converts to EST,
and injects it into the essay-page-header__meta div.

Usage:
    python retroactive_pub_datetime.py \
        --token-file path/to/.publish-config \
        --repo DonovanBerry11/anthology
"""

import argparse
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path


def run(cmd, cwd=None, check=True):
    result = subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True, text=True)
    if check and result.returncode != 0:
        print(f"Command failed: {cmd}", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(1)
    return result.stdout.strip()


def utc_to_est(utc_dt_str):
    """
    Parse a git log --format="%ai" timestamp (e.g. '2026-05-10 14:32:01 +0000')
    and convert to EST (UTC-5). Returns a formatted string like '10 May 2026, 9:32 AM'.
    """
    # git %ai format: 'YYYY-MM-DD HH:MM:SS +ZZZZ'
    # Parse with UTC offset
    try:
        dt = datetime.strptime(utc_dt_str[:19], "%Y-%m-%d %H:%M:%S")
        # Extract offset
        offset_str = utc_dt_str[20:].strip()
        sign = 1 if offset_str[0] == '+' else -1
        offset_h = int(offset_str[1:3])
        offset_m = int(offset_str[3:5])
        offset = timedelta(hours=offset_h, minutes=offset_m) * sign
        dt_utc = dt.replace(tzinfo=timezone.utc) - offset
        # Convert to EST (UTC-5)
        est = timezone(timedelta(hours=-5))
        dt_est = dt_utc.astimezone(est)
        return dt_est.strftime("%-d %B %Y, %-I:%M %p")
    except Exception as e:
        print(f"  Warning: could not parse timestamp '{utc_dt_str}': {e}", file=sys.stderr)
        return None


def patch_html_file(html_path, pub_datetime_str):
    """
    Find <div class="essay-page-header__meta">...</div> and replace its content
    with '{existing_content} · Published {pub_datetime_str} EST'.

    Skips files that already contain 'Published' in the meta div (already patched).
    Returns True if patched, False if skipped.
    """
    content = html_path.read_text(encoding="utf-8")

    # Match the meta div (single line, as generated by our scripts)
    pattern = r'(<div class="essay-page-header__meta">)(.*?)(</div>)'
    match = re.search(pattern, content)
    if not match:
        print(f"  ⚠  No meta div found in {html_path.name} — skipping")
        return False

    existing = match.group(2)

    # Skip if already stamped
    if 'Published' in existing:
        print(f"  ↩  {html_path.name} already has publication datetime — skipping")
        return False

    new_content = f'{existing} &middot; Published {pub_datetime_str} EST'
    new_div = f'{match.group(1)}{new_content}{match.group(3)}'
    patched = content[:match.start()] + new_div + content[match.end():]
    html_path.write_text(patched, encoding="utf-8")
    return True


def get_first_commit_timestamp(repo_path, relative_file_path):
    """
    Get the timestamp of the FIRST commit that introduced this file.
    Returns a git %ai format string, or None if not found.
    """
    result = subprocess.run(
        f'git log --follow --format="%ai" -- "{relative_file_path}"',
        shell=True, cwd=repo_path, capture_output=True, text=True
    )
    if result.returncode != 0 or not result.stdout.strip():
        return None
    # Last line is the oldest (first) commit
    lines = [l.strip().strip('"') for l in result.stdout.strip().splitlines() if l.strip()]
    return lines[-1] if lines else None


def main():
    parser = argparse.ArgumentParser(
        description="Retroactively add publication datetimes to Anthology HTML pages"
    )
    parser.add_argument("--token-file", required=True,
                        help="Path to .publish-config containing GitHub PAT")
    parser.add_argument("--repo", default="DonovanBerry11/anthology",
                        help="GitHub repo in owner/name format")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be patched without writing or pushing")
    args = parser.parse_args()

    token = Path(args.token_file).read_text().strip()
    clone_dir = Path("/tmp/anthology-retroactive-patch")

    # 1. Clone
    print("Cloning repo...")
    if clone_dir.exists():
        shutil.rmtree(clone_dir)
    run(f'git clone "https://DonovanBerry11:{token}@github.com/{args.repo}.git" {clone_dir}')
    run(f'git config user.email "donovanberry11@gmail.com"', cwd=clone_dir)
    run(f'git config user.name "Donovan Berry"', cwd=clone_dir)

    # 2. Identify all HTML files in the content directories
    sections = ["essays", "notes", "dispatches", "uk-politics", "us-sports"]
    html_files = []
    for section in sections:
        section_dir = clone_dir / section
        if section_dir.exists():
            html_files.extend(sorted(section_dir.glob("*.html")))

    print(f"\nFound {len(html_files)} HTML files to process.\n")

    patched_files = []
    for html_path in html_files:
        relative = html_path.relative_to(clone_dir)
        print(f"Processing: {relative}")

        # Get first commit timestamp
        ts = get_first_commit_timestamp(clone_dir, str(relative))
        if not ts:
            print(f"  ⚠  No git history found for {relative} — using fallback timestamp")
            # Fallback: use 10 May 2026, 12:00 PM (known publication session)
            ts = "2026-05-10 17:00:00 +0000"

        pub_dt = utc_to_est(ts)
        if not pub_dt:
            print(f"  ⚠  Could not parse timestamp for {relative} — skipping")
            continue

        print(f"  → First commit: {ts}  →  EST: {pub_dt}")

        if args.dry_run:
            print(f"  [DRY RUN] Would inject: Published {pub_dt} EST")
            continue

        patched = patch_html_file(html_path, pub_dt)
        if patched:
            patched_files.append(str(relative))
            print(f"  ✓ Patched")

    if args.dry_run:
        print(f"\n[DRY RUN] Would patch {len(html_files)} files. No changes written.")
        return

    if not patched_files:
        print("\nNo files needed patching.")
        return

    # 3. Commit and push
    print(f"\nCommitting {len(patched_files)} patched files...")
    files_arg = " ".join(f'"{f}"' for f in patched_files)
    run(f'git add {files_arg}', cwd=clone_dir)
    run(
        f'git commit -m "Add retroactive publication datetimes to {len(patched_files)} HTML pages"',
        cwd=clone_dir
    )
    run('git push', cwd=clone_dir)

    print(f"\n✅ Retroactive datetime patch complete — {len(patched_files)} files updated.")
    print("   (Vercel deployment typically takes under 60 seconds)")


if __name__ == "__main__":
    main()
